void squares (){};
float topLeftSquareX, topLeftSqaureY, topLeftSqaureHeight,topLeftSqaureWidth;
float topMiddleSquareX, topMiddleSqaureY, topMiddleSqaureHeight,topMiddleSqaureWidth;
float topRightSquareX, topRightSqaureY, topRightSqaureHeight,topRightSqaureWidth;

float middleLeftSquareX, middleLeftSqaureY, middleLeftSqaureHeight,middleLeftSqaureWidth;
float middleCenterSquareX, middleCenterSqaureY, middleCenterSqaureHeight,middleCenterSqaureWidth;
float middleRightSquareX, middleRightSqaureY, middleRightSqaureHeight,middleRightSqaureWidth;

float bottomLeftSquareX, bottomLeftSqaureY, bottomLeftSqaureHeight,BottomLeftSqaureWidth;
float bottomMiddleSquareX, bottomMiddleSqaureY, bottomMiddleSqaureHeight,BottomMiddleSqaureWidth;
float bottomRightSquareX, bottomRightSqaureY, bottomRightSqaureHeight,BottomRightSqaureWidth;
